### ISSUE TITLE
Long run times

### ISSUE THREAD

**Issue by ccs76** [luntergroup/octopus#72] opened 2019-07-29 17:45 UTC
Hello

Thanks a lot for the program. I'm trying to call de novo variants in my trio, its normal takes 5 days? with Varscan just takes 1-2 hours.

Thanks

**Comment by ahstram** [comment] 2019-07-30 03:06
I've been experiencing similar issues with octopus-0.6.3-beta. Haven't got around to writing a bug report with an example dataset yet, but it seems to happen primarily in "cancer" mode (paired tumor+normal samples), with high-depth (1000x) data when downsampling is turned off.  I have not experienced the issue when running the same samples individually (i.e., "germline" mode).

Here's a typical problematic command:

`octopus-0.6.3-beta/bin/octopus --threads 8 -R hs37d5.fa -I normal.17-03.contig.bam tumor.17-03.contig.bam --normal-sample normal -t 17-03.bed             --working-directory $TMPDIR -f off --annotations forest --config v3.config -o 17-03.vcf`

With the config file:

```
caller=cancer
somatics-only=yes
disable-downsampling=yes
min-kmer-prune=5
min-bubble-score=20
somatic-snv-mutation-rate=5e-4
somatic-indel-mutation-rate=1e-05
min-expected-somatic-frequency=0.004
min-credible-somatic-frequency=0.001
max-somatic-haplotypes=3
target-working-memory=50G
tumour-germline-concentration=5
somatic-filter-expression=GQ < 200 | MQ < 30 | SB > 0.2 | SD[.25] > 0.1 | BQ < 40 | DP < 100 | MF > 0.1 | AD < 5 | CC > 1.1 | GQD > 2 | REB > 0.2
```

I have my panel split into ~300 equally sized regions, certain regions seem to more susceptible to long run times than others. Typical regions take ~2 hours to run, but others can take up to 5 days.

A problematic region will typically "jam" up right around 99% complete. For example, the following output:
```
$ tail octopus-D1-D2_pure.6-0d.o7566706
[2019-07-25 08:10:02] <INFO>     6:170058227            91.1%          25m 14s            2m 33s
[2019-07-25 08:13:03] <INFO>     6:170068068            92.2%          28m 15s            2m 30s
[2019-07-25 08:13:04] <INFO>     6:170104446            93.2%          28m 16s             2m 9s
[2019-07-25 08:13:05] <INFO>     6:170118085            94.2%          28m 17s            1m 47s
[2019-07-25 08:13:06] <INFO>     6:170153702            95.4%          28m 17s            1m 25s
[2019-07-25 08:13:06] <INFO>     6:170167013            96.4%          28m 18s             1m 4s
[2019-07-25 08:13:11] <INFO>     6:170190200            97.4%          28m 22s               45s
[2019-07-25 08:37:47] <INFO>      6:30996097            98.4%          52m 58s               50s
[2019-07-25 09:49:25] <INFO>      6:30997203            99.5%            2h 4m               39s
[2019-07-25 09:53:11] <INFO>      6:30998103            99.6%            2h 8m               24s
$ date
Mon Jul 29 19:41:26 PDT 2019
```
That is, the process has taken 4+ days to complete the last 0.4% of processing, which it originally estimated to take 24 seconds.

I've tried changing the --target-read-buffer-footprint parameter to values as low as 600MB and as high as 300MB, without success. I've also changed --max-reference-cache-footprint to 4GB, without success.

I've run association tests to see if the problematic regions are higher depth than regions that only take an hour or two to run. They are not-- measuring by both max depth and average depth, in both the normal & tumor sample, there is no association between sequencing depth and run time.

I'm typically runninng analyses with 8 cores, but have tried with 1 core, and the problem persists.

I've also done some strace'ing, and found that most of the threads are in a status like:

`futex(0x2ec04f0, FUTEX_WAKE, 2147483647) = 0`

And the thread which the others are waiting on typically has a bunch of calls like:

`mprotect(0x2b48a0031000, 40960, PROT_READ|PROT_WRITE) = 0`

occuring.

I've experienced the issue with both CentOS 6.10 and Ubuntu 18.04 environments. 

Is there anything that may help, other than turning on downsampling? I am looking at tumor samples with very low tumor concentration levels, so I would prefer to keep downsampling off.

**Comment by dancooke** [comment] 2019-08-03 20:31
@ccs76 What is your command, which version of Octopus are you using and how did you install? What system are you using? Please provide the output to `octopus --version`. Octopus' default settings are geared towards accuracy rather than runtime, so while I can't say that 5 days is 'normal' - as this depends on the details above - it will almost certainly be the case that Octopus won't be as fast as Varscan. However, Octopus will probably give more accurate results. You can trade off accuracy for runtime by changing Octopus' parameters (e.g. by adding `--fast` to your command, read the docs for more ways to adjust performance).

@ahstram Thanks for the detailed report. It's true that Octopus can get 'stuck' in certain regions, particularly when using the more complex calling models such as `cancer`. The problem is not so much depth (although this is a factor), but the number of candidate variants (and therefore haplotypes) in the region. In the vast majority of cases the cause is mapping errors due to low complexity sequence or incomplete reference sequence. I've put some work into being able to detect and skip these 'uncallable' regions since v0.6.3b that should help prevent this issue. The updates will be available in the next version of Octopus. Until then, one option is to try to identify where Octopus is getting stuck (if you send me the output of `--debug` log then I should be able to tell you), and [manually skip](https://github.com/luntergroup/octopus/wiki/How-to:-Call-targeted-regions) these regions. If you're running the same pipeline over multiple samples then this should be safe to do.

**Comment by ahstram** [comment] 2019-08-05 18:41
@dancooke 

Great! I'm glad to hear that there will soon be a feature to automatically skip over uncallable regions. It became apparent to me during investigation that this was not a bug in octopus entering some sort of near-infinite loop, but rather Octopus doesn't account for complex regions well when estimating run times, which is understandable. Furthermore, one only thread typically gets caught up on an uncallable region, and the other threads sit in the FUTEX_WAIT state until the uncallable region is complete.

For your purposes (may be helpful for testing the new escape-uncallable-regions feature), I've attached a particularly problematic dataset, which I isolated from a larger dataset that took 5 days to run.

Here's the execution command:

```
\time -v octopus-0.6.3-beta/bin/octopus -R hs37d5.fa -I tumor.bam normal.bam \


    --normal-sample normal -f off --disable-downsampling yes -t region.bed \
    --debug $PWD/debug.log -o $PWD/output.vcf
```
This particular dataset takes ~45 minutes to run, which is very long considering it's a 500bp region with ~3000x tumor coverage and ~900x normal coverage.

Here's the debug.log file, as well as necessary input files:

[debug.log](https://github.com/luntergroup/octopus/files/3468906/debug.log)
[normal.bam.gz](https://github.com/luntergroup/octopus/files/3468909/normal.bam.gz) (had to gzip to upload)
[tumor.bam.gz](https://github.com/luntergroup/octopus/files/3468913/tumor.bam.gz) (had to gzip to upload)
[region.bed.txt](https://github.com/luntergroup/octopus/files/3468915/region.bed.txt) (remove ".txt" from filename)

Finally, for others reading this: the best way I've found to mitigate the extreme runtime issue is to exclude the UCSC "repeat masker" regions, which I generated by:

1. Go to https://genome.ucsc.edu/cgi-bin/hgTables
2. Select your relevant reference genome
3. Select "Repeats" group, 
4. Select "Repeat Masker" track, 
5. Select  "BED" output format, 
6. Run "sed -i 's/^chr//'" on the resulting file to remove "chr" from the ref names
7. Use "-k" to exclude the repeatMasker regions from your analysis. 

I look forward to your next release!

Alex

**Comment by dancooke** [comment] 2019-08-07 18:12
@ahstram Many thanks for the great bug report - makes life so much easier! This region turned out not to be what I would call 'uncallable'; rather it just so happens the assembler proposes a few large deletions that cause a large haplotype block to be evaluated. What was actually causing such a slow-down was the evaluation of the somatic variant model with 2 somatic haplotypes. I realised that this evaluation wasn't always respecting the value of `--max-genotypes`, which limits the number of 'somatic' genotypes considered by the model and is one of the main determinant of runtime in this model. I've addressed this in 75b76131198bf40c5cda88c0fbe1ad7d088a4c28 - I still need to test this change to ensure it doesn't impact accuracy but my feelings is that it won't. On my machine this reduces runtime for this region from ~1 hour to ~8 minutes.

**Comment by ccs76** [comment] 2019-08-07 18:31
Hello

Thanks for the help, sorry for the delay to answer,  I installed the last
version

octopus version 0.6.3-beta (develop 7eab0cd)
Target: x86_64 Linux 4.4.0-157-generic
SIMD extension: SSE2
Compiler: GNU 9.1.0
Boost: 1_70

I tried with

octopus -R hg38.fa -I recal_reads02.bam recal_reads06.bam recal_reads08.bam
--pedigree 268.ped --output test268.vcf

octopus -R hg38.fa -I recal_reads02.bam recal_reads06.bam recal_reads08.bam
--pedigree 268.ped --denovos-only --very-fast --output test268.vcf

octopus -R hg38.fa -I recal_reads08.bam recal_reads06.bam recal_reads02.bam
-M sample06 -F sample08 --output test268.vcf

octopus -R hg38.fa -I recal_reads08.bam recal_reads06.bam recal_reads02.bam
-M sample06 -F sample08 --output test268.vcf

No luck reducing the time lapsing

I have the same problem If I use mpileup with bcftools but with varscan
goes fine and freebayes mpileup. So Im pretty confuse why goes fast in some
programs and others need like weeks. Im just interested on call de novo
variants and compare between different programs.


[2019-08-07 20:23:01] <INFO> octopus v0.6.3-beta (develop 7eab0cd)
[2019-08-07 20:23:01] <INFO> Copyright (c) 2015-2019 University of Oxford
[2019-08-07 20:23:01] <INFO>
------------------------------------------------------------------------
[2019-08-07 20:23:45] <INFO> Done initialising calling components in 43s
[2019-08-07 20:23:45] <INFO> Detected 3 samples: "sample02" "sample06"
"sample08"
[2019-08-07 20:23:45] <INFO> Invoked calling model: trio
[2019-08-07 20:23:45] <INFO> Processing 3,088,286,401bp with a single
thread (4 cores detected)
[2019-08-07 20:23:45] <INFO> Writing filtered calls to
"/media/cri/TRIO/OCTOPUS/test268.vcf"
[2019-08-07 20:23:45] <INFO>
------------------------------------------------------------------------
[2019-08-07 20:23:45] <INFO>      current      |                   |
time      |     estimated
[2019-08-07 20:23:45] <INFO>      position     |     completed     |
taken     |     ttc
[2019-08-07 20:23:45] <INFO>
------------------------------------------------------------------------


Cristina

**Comment by dancooke** [comment] 2019-08-07 18:54
@ccs76 You're not going to get runtimes in order of hours to call three whole genomes jointly using a single thread, sorry. With the greatest respect to VarScan, it is implements a far simpler algorithm than haplotype-based callers such as Octopus (e.g. there is no de novo assembly, realignment of reads, or consideration of haplotypes), and this is reflected in both accuracy and runtime. If your main concern is runtime of the variant caller then I'd just use VarScan, but be sure to consider how much additional analysis time you'll spend by using a fast caller compared with a 'slow' caller that is more accurate (there may be orders of magnitude difference in the number of called _de novo_ mutations called). If you want accurate variant calls **and** fast runtimes then you'll have to use more computational resources.

**Comment by ccs76** [comment] 2019-08-07 19:46
Thanks Daniel

Thanks a lot for the explanation, it helps me to understand a bit more, If
I use de T option seems is  a possibility for my pc to handle it, but the
results may differ if do one by one chr? All those recal_reads bam files I
had processed before with aligment, mark duplicates, realignment, apply
BQSR...and got also my final  vcf files doing hard filtering with GATK.
Calling de novo varinats from vcf files or directly from my bam files, may
differ a lot in the results? Im bit confuse about that. Octopus has the
option to call de novo variants from vcf files instead bam files? Just
maybe be silly questions, sorry for disturb and thanks!.

octopus -R hg38.fa -I recal_reads08.bam recal_reads06.bam recal_reads02.bam
-M sample06 -F sample08 -T 1 2 --threads 4 --denovos-only --very-fast
--output test268.vcf
[2019-08-07 21:20:23] <INFO>
------------------------------------------------------------------------
[2019-08-07 21:20:23] <INFO> octopus v0.6.3-beta (develop 7eab0cd)
[2019-08-07 21:20:23] <INFO> Copyright (c) 2015-2019 University of Oxford
[2019-08-07 21:20:23] <INFO>
------------------------------------------------------------------------
[2019-08-07 21:21:01] <INFO> Done initialising calling components in 37s
[2019-08-07 21:21:01] <INFO> Detected 3 samples: "sample02" "sample06"
"sample08"
[2019-08-07 21:21:01] <INFO> Invoked calling model: trio
[2019-08-07 21:21:01] <INFO> Processing 491,149,951bp with 4 threads (4
cores detected)
[2019-08-07 21:21:01] <INFO> Writing filtered calls to
"/media/cri/TRIO/OCTOPUS/test268.vcf"
[2019-08-07 21:22:56] <INFO>
------------------------------------------------------------------------
[2019-08-07 21:22:56] <INFO>      current      |                   |
time      |     estimated
[2019-08-07 21:22:56] <INFO>      position     |     completed     |
taken     |     ttc
[2019-08-07 21:22:56] <INFO>
------------------------------------------------------------------------
[2019-08-07 21:27:35] <INFO>      1:63913760             0.5%           4m
39s           15h 25m

**Comment by dancooke** [comment] 2019-08-07 20:01
Calling *de novo* variants from a VCF file is simple - you just have to look for Mendelian vocations in `GT` fields (and possible use some calculation involving pre-computed genotype likelihoods). Calling *de novo* variants from BAM files is substantially more work - this is the step that gets you to VCF. Octopus generates a VCF, but apposed to other methods it calls and marks *de novo* variants in one step.

Regarding your question about splitting up the call regions, the results *should* be the same but in practice they can differ due to use of read statistics and boundary artefacts. If splitting by contigs this is unlikely to be a problem however.

Octopus doesn't require any of the BAM pre-processing that GATK recommends so you can avoid some compute time there.

**Comment by ahstram** [comment] 2019-08-08 06:20
@dancooke , thanks for the quick turn-around! 

I've incorporated your commit into my checkout & am wondering what value you suggest for --max-genotypes? I see that the Octopus default is 5000, I was able to reduce runtime to ~20 minutes by setting it to "50". Do you have a suggested value?

**Comment by ahstram** [comment] 2019-08-09 05:45
@dancooke 

It looks ilke the 75b7613 commit does reduce runtimes without having to modify --max-genotypes parameter for newer versions of Octopus, but not for the octopus-0.6.3-beta release. I tried cherry-picking the 75b7613 commit against 0.6.3-beta release & it didn't seem to have any impact on runtime, whereas just using the latest commit on develop branch, including 75b7613 does seem to improve my runtimes.

**Comment by dancooke** [comment] 2019-08-09 08:01
@ahstram 

Yes I noticed that. I haven't had time to look into why that is yet - there have been a number of substantial changes on develop since v0.6.3b. One possibility is that the set of candidate variants is different due to tweaks in the somatic candidate generators, and it just so happens the new set can be evaluated more quickly.

Regarding a good value for `--max-genotypes`... 50 would be pretty low. In order to satisfy this limit the algorithm must remove candidate genotypes before evaluation of the full probabilistic model. Heuristics are used to do this, and although these are generally pretty good at leaving the most probable genotypes (according to the model) intact, 50 doesn't leave much margin for error.

**Comment by ahstram** [comment] 2019-08-09 15:58
@dancooke 
thanks for confirming. Sounds like I'll just have to let my current analysis finish running (don't have time to start it from scratch with a checkout of the current development branch, which would be necessary since the output has changed a bit since the 0.6.3-beta release). I'll also leave --max-genotypes at its default behavior. Luckily my current analysis has the UCSC RepeatMasker regions excluded, which does help things a bit.

**Comment by ahstram** [comment] 2019-08-11 20:43
@dancooke do you have an idea of when the next version of octopus will be released?

I ask because the current development branch of octopus seems to finish my problematic regions in ~8 hours, whereas the 0.6.3-beta release can take 5+ days. So, I'd definitely like to move to a newer version, but ideally would like to use a stable release, if at all possible. 

Thanks,

Alex

**Comment by dancooke** [comment] 2019-08-12 14:33
@ahstram Might be another couple of weeks... I'm not planning any more major changes but still need to iron out a few issues and re-run all my tests.

**Comment by ahstram** [comment] 2019-08-12 17:41
@dancooke great, thanks!

**Comment by rspreafico** [comment] 2019-12-09 16:45
Same here, long running times in `polyclone` mode. As noted by others, octopus takes exponentially longer times as it approaches the end of the run. I tried both `0.6.3-beta` and `0.7.0-develop` (as of Dec 8 2019) with similar results. Genome size is ~10kb in 8 segments, and coverage is between 5000 and 10000X (which is normal, for mixed samples, as one is typically interested in variant frequency down to 1%). 

Calling with:

```
octopus --threads 8 -C polyclone --max-genotypes 30 --max-haplotypes 100 --downsample-above 6000 --keep-unfiltered-calls --bamout-type FULL --max-clones 30 --min-clone-frequency 0.01 --variant-discovery-mode ILLUMINA --sequence-error-model PCR.HISEQ-2500 -R ref.fa -I mappings.bam -o variants.vcf --bamout evidence.bam 
```

Output:

```
[2019-12-08 15:25:27] <INFO> ------------------------------------------------------------------------
[2019-12-08 15:25:27] <INFO> octopus v0.7.0 (develop a8f22e09)
[2019-12-08 15:25:27] <INFO> Copyright (c) 2015-2019 University of Oxford
[2019-12-08 15:25:27] <INFO> ------------------------------------------------------------------------
[2019-12-08 15:25:43] <WARN> The polyclone calling model is still in development. Do not use for production work!
[2019-12-08 15:25:43] <INFO> Done initialising calling components in 15s
[2019-12-08 15:25:43] <INFO> Detected 1 sample: "P0678M00003"
[2019-12-08 15:25:43] <INFO> Invoked calling model: polyclone
[2019-12-08 15:25:43] <INFO> Processing 13,158bp with 8 threads (16 cores detected)
[2019-12-08 15:25:43] <INFO> Writing filtered calls to "/mnt/ebs/flu/P0678M00003.vcf"
[2019-12-08 15:25:43] <INFO> ------------------------------------------------------------------------
[2019-12-08 15:25:43] <INFO>      current      |                   |     time      |     estimated
[2019-12-08 15:25:43] <INFO>      position     |     completed     |     taken     |     ttc
[2019-12-08 15:25:43] <INFO> ------------------------------------------------------------------------
[2019-12-08 15:25:51] <INFO> NC_026433.1:1701           13.5%               8s               51s
[2019-12-08 15:25:52] <INFO> NC_026438.1:160            14.7%               8s               48s
[2019-12-08 15:25:52] <INFO> NC_026438.1:294            15.8%               9s               47s
[2019-12-08 15:26:05] <INFO> NC_026431.1:982            23.6%              22s            1m 11s
[2019-12-08 15:26:12] <INFO> NC_026438.1:474            24.6%              29s            1m 29s
[2019-12-08 15:26:17] <INFO> NC_026432.1:863            31.1%              34s            1m 16s
[2019-12-08 15:26:20] <INFO> NC_026438.1:713            33.4%              37s            1m 14s
[2019-12-08 15:26:26] <INFO> NC_026438.1:1004           35.6%              42s            1m 16s
[2019-12-08 15:26:26] <INFO> NC_026436.1:251            37.4%              43s            1m 12s
[2019-12-08 15:26:31] <INFO> NC_026438.1:1261           39.0%              48s            1m 15s
[2019-12-08 15:26:32] <INFO> NC_026438.1:1514           41.0%              48s            1m 10s
[2019-12-08 15:26:32] <INFO> NC_026438.1:1719           42.5%              48s             1m 6s
[2019-12-08 15:26:32] <INFO> NC_026438.1:1988           44.6%              49s             1m 1s
[2019-12-08 15:26:46] <INFO> NC_026435.1:186            46.7%            1m 3s            1m 12s
[2019-12-08 15:26:47] <INFO> NC_026435.1:355            48.0%            1m 3s             1m 9s
[2019-12-08 15:26:50] <INFO> NC_026436.1:297            49.2%            1m 6s             1m 9s
[2019-12-08 15:26:50] <INFO> NC_026435.1:683            50.9%            1m 6s             1m 5s
[2019-12-08 15:26:50] <INFO> NC_026435.1:856            52.2%            1m 6s             1m 1s
[2019-12-08 15:26:56] <INFO> NC_026434.1:135            53.6%           1m 13s             1m 4s
[2019-12-08 15:26:56] <INFO> NC_026434.1:1410           63.3%           1m 13s               43s
[2019-12-08 15:27:01] <INFO> NC_026437.1:516            66.7%           1m 17s               39s
[2019-12-08 15:27:02] <INFO> NC_026437.1:664            67.8%           1m 18s               37s
[2019-12-08 15:27:04] <INFO> NC_026437.1:818            69.0%           1m 21s               36s
[2019-12-08 15:27:25] <INFO> NC_026435.1:1037           70.4%           1m 41s               43s
[2019-12-08 15:27:33] <INFO> NC_026437.1:962            71.4%           1m 49s               44s
[2019-12-08 15:28:11] <INFO> NC_026435.1:1280           73.3%           2m 28s               54s
[2019-12-08 15:29:08] <INFO> NC_026435.1:1611           75.8%           3m 25s             1m 6s
[2019-12-08 15:29:28] <INFO> NC_026435.1:1868           77.8%           3m 44s             1m 5s
[2019-12-08 15:29:38] <INFO> NC_026435.1:2028           79.0%           3m 54s             1m 3s
[2019-12-08 15:30:55] <INFO> NC_026435.1:2202           80.3%           5m 11s            1m 17s
[2019-12-08 15:37:06] <INFO> NC_026436.1:445            81.5%          11m 23s            2m 36s
[2019-12-08 16:07:57] <INFO> NC_026437.1:1264           84.0%          42m 13s            8m 11s
[2019-12-08 16:08:05] <INFO> NC_026437.1:1646           86.9%          42m 21s            6m 29s
[2019-12-08 16:08:06] <INFO> NC_026437.1:1679           87.1%          42m 22s            6m 20s
[2019-12-08 16:08:44] <INFO> NC_026437.1:1796           88.0%              43m            5m 55s
[2019-12-08 16:25:01] <INFO> NC_026437.1:2091           90.3%          59m 18s            6m 29s
[2019-12-08 16:25:01] <INFO> NC_026437.1:2151           90.7%          59m 18s             6m 7s
[2019-12-08 17:46:43] <INFO> NC_026436.1:489            90.9%           2h 20m           14m 23s
[2019-12-08 17:50:14] <INFO> NC_026436.1:506            91.0%           2h 24m           14m 25s
[2019-12-08 17:57:13] <INFO> NC_026436.1:533            91.2%           2h 31m           14m 44s
[2019-12-08 18:00:38] <INFO> NC_026436.1:682            92.4%           2h 34m               13m
[2019-12-08 18:00:57] <INFO> NC_026436.1:860            93.7%           2h 35m           10m 29s
[2019-12-08 18:08:43] <INFO> NC_026436.1:977            94.6%           2h 43m            9m 19s
[2019-12-08 18:08:55] <INFO> NC_026436.1:991            94.7%           2h 43m             9m 9s
[2019-12-08 18:09:26] <INFO> NC_026436.1:1006           94.8%           2h 43m            8m 59s
[2019-12-08 18:09:31] <INFO> NC_026436.1:1066           95.3%           2h 43m            8m 15s
[2019-12-08 18:20:59] <INFO> NC_026436.1:1088           95.4%           2h 55m            8m 27s
[2019-12-08 21:39:49] <INFO> NC_026436.1:1105           95.6%           6h 14m           17m 37s
[2019-12-08 23:48:11] <INFO> NC_026438.1:2182           96.3%           8h 22m           19m 13s
[2019-12-09 06:57:49] <INFO> NC_026438.1:2221           96.6%          15h 32m           32m 37s
[2019-12-09 06:57:49] <INFO> NC_026438.1:2280           97.1%          15h 32m           28m 32s
```

(still running)

**Comment by dancooke** [comment] 2019-12-09 17:42
@rspreafico Likely the largest contributor to this is the `--max-clones 30` setting. Are you expecting to see this many unique stains in your data? Consider that to call this many strains Octopus could potentially have to consider `sum(100Ci) for i = 1..30 ~= 5*10^25` possible genotypes. Obviously it doesn't actually do this since some heuristics are used to eliminate obviously false genotypes, but it gives an indication of the problem scale.

If you're able to provide me with the BAM and reference files then I'm happy to take a look and try to find ways to improve runtimes.

**Comment by rspreafico** [comment] 2019-12-09 17:50
@dancooke That would be awesome, thanks! I don't know how many clones end up in my sample, but 30 is possible. I would expect a distribution with a long right tail, where maybe a handful of clones dominate, and then a greater number (probably greater than 30) is present at lower frequencies (some above 1%, some below 1%). 

I would be happy to provide an example BAM. Do you have a drop box I can upload to?

**Comment by dancooke** [comment] 2019-12-09 19:02
@rspreafico Yes but I'll need your email to give you permission to upload to it, or you can upload to your own shared dropbox and give me a viewing link if that's easier.

**Comment by rspreafico** [comment] 2019-12-09 19:56
Thanks Dan, I just sent my email address via Gitter.

**Comment by dancooke** [comment] 2019-12-15 18:31
@rspreafico Please try the latest develop branch version - it should be quite a bit faster. The main problem turned out to be the assembler generating way too many candidates for high depth data.

My command is

```shell
octopus -C polyclone \
    -R GCF_001343785.1_ViralMultiSegProj274766_genomic.fa \
    -I sample.bam \
    --disable-downsampling \
    --max-clones 30 \
    --max-genotypes 10000 \
    --min-clone-frequency 0.01 \
    --sequence-error-model PCR.HISEQ-2500 \
    -o sample.octopus.vcf \
    --threads \
    --bamout evidence.bam \
    --bamout-type FULL \
    --keep-unfiltered-calls
```

**Comment by rspreafico** [comment] 2019-12-17 17:48
Hi @dancooke - thanks for looking into that and for the quick fix! 

I tried the latest version. Rather than running on the same dummy sample (since I am sure you did it yourself), I tried it on a real sample I worked on recently (3kb reference, 50000x coverage). The run completed very fast, in a matter of few minutes, but there were no variants returned (not even in the unfiltered VCF). On same reference and bam file, LoFreq returned a few tens variants, some close to 100% frequency and some close to 1% frequency. This being a real sample, I cannot share it.

I will now try to run octopus on the previous dummy data that I shared just to make sure it works in my hands on that, but wanted to give a heads-up. Given the high coverage, I would tend to believe any call from LoFreq above the 1% frequency threshold, since LoFreq is notoriously not that sensitive but specific enough. The high coverage should offset the low sensitivity, and so the callset from LoFreq could be a decent approximation of expectations from octopus?

**Comment by rspreafico** [comment] 2019-12-17 19:03
Hi @dancooke, I tested on shared dummy data. First, running times are incredibly better. Time to completion estimate is also much more accurate.

Anecdotally, octopus seems a little less sensitive than LoFreq, with some calls just above 1% frequency performed by both tools (both unfiltered) and others made only by lofreq.

However, there is something funky going on. Calls are missing entirely for some contigs. Even calls made at near 100% frequency. You can see that in the dummy data shared. I think that explains why I got no calls in previous post (in that case, reference is a single contig).

**Comment by dancooke** [comment] 2019-12-17 19:08
@rspreafico Okay, will take a look. Can you post a couple of the low frequency variants that lofreq is calling but Octopus is missing? I assume that you know these to be true?

**Comment by dancooke** [comment] 2020-08-19 12:40
Closing for now as I believe Octopus runtimes to now be much better than what they were (although still something I'd like to improve long-term). Please re-open and continue this issue for glaring runtimes related problems.

**Closed by dancooke** 2020-08-19 12:40 UTC
Labels: performance
