### ISSUE TITLE
Octopus outputs invalid alternate allele

### ISSUE THREAD

**Issue by DBS-Max** [luntergroup/octopus#100] opened 2019-12-13 17:57 UTC
**Describe the bug**
Trying to impute 1x sample using Beagle5.1 and received the following error on vcf file produced by octopus: `ERROR: invalid ALT allele at chr1:9144584 [*AAA]`

**Version**

```shell
$ octopus --version
octopus version 0.6.3-beta (release/0.6.3-beta 8b0e2968)
Target: x86_64 Linux 5.0.0-1023-azure
Compiler: GNU 8.3.0
Boost: 1_71

and

octopus version 0.7.0 (develop 0aa9e574)
Target: x86_64 Linux 5.0.0-1023-azure
SIMD extension: AVX2
Compiler: GNU 9.2.0
Boost: 1_71
```

**Comment by DBS-Max** [comment] 2019-12-13 17:58
Ah, read the documentation, gotta turn the --legacy option on. Feel free to close!

**Comment by DBS-Max** [comment] 2019-12-13 18:03
The develop version doesn't recognize the --legacy command, 0.6.3b does.

**Comment by DBS-Max** [comment] 2019-12-13 19:27
Command (octopus 0.6.3b):
```
octopus \
      -R Homo_sapiens_assembly38.fasta \
      -I 1_NA12878.bam \
      -t octopus_intervals \
      -o 1_NA12878.bcf \
      --sequence-error-model PCR-FREE.NOVASEQ \
      --threads 16 \
      --legacy
```

Still outputs alternate alleles with a * causing beagle to throw an error.

**Comment by dancooke** [comment] 2019-12-14 22:25
I'm removing the `--legacy` option in v0.7.0. I'll probably include a script to replicate the functionality.

**Comment by DBS-Max** [comment] 2019-12-14 22:26
Okay,

How should I go about it in the meantime? Just get rid of all the * characters?

Cheers,

Max.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10




[cid:Destiny-Bioscience_colour_223e1346-07b0-482e-a6d0-4a36fc26dd2e.png]<http://destinyorganics.ca/>


Max Hargreaves,

Scientist - Bioinformatics

Direct 587.453.0650


*** Destiny Bioscience Global Corp. *** This email is confidential. If you are not the intended recipient, you must not disclose or use the information contained in it. If you have received this email in error, please notify us immediately by return email and delete the email and any attachments. Any personal views or opinions expressed by the writer may not necessarily reflect the views or opinions of Destiny Bioscience Global Corp.

**Comment by dancooke** [comment] 2019-12-14 22:33
> How should I go about it in the meantime? Just get rid of all the * characters?

You will need to remove any `ALT` alleles containing a `*` character, and then set any `GT` fields pointing to these alleles to `0` (i.e. `REF`). You might also need to recompute any annotation values that refer to `ALT` alleles (e.g. `AC`).

**Comment by DBS-Max** [comment] 2019-12-16 19:14
Okay, I just deleted all variants with a *, easy enough for now.

**Comment by dancooke** [comment] 2019-12-19 20:46
Closing as not a bug.

**Closed by dancooke** 2019-12-19 20:46 UTC
Labels: question
