### ISSUE TITLE
core dumped (bioconda)

### ISSUE THREAD

**Issue by micknudsen** [luntergroup/octopus#27] opened 2018-04-26 13:51 UTC
Hi,

I have installed octopus using bioconda, but when I try to run it, I just get a core dump. Does anybody have an idea what could be wrong?

Thanks!

```
[michaelk@fe1 ~]$ conda create -n octopus octopus -y
Fetching package metadata ...................
Solving package specifications: .

Package plan for installation in environment /home/michaelk/anaconda3/envs/octopus:

The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-1            conda-forge
    ca-certificates: 2018.4.16-0        conda-forge
    curl:            7.59.0-1           conda-forge
    htslib:          1.7-0              bioconda
    icu:             58.2-0             conda-forge
    krb5:            1.14.6-0           conda-forge
    libgcc:          7.2.0-h69d50b8_2
    libgcc-ng:       7.2.0-hdf63c60_3
    libssh2:         1.8.0-2            conda-forge
    libstdcxx-ng:    7.2.0-hdf63c60_3
    octopus:         0.3.3a-htslib1.7_1 bioconda
    openssl:         1.0.2o-0           conda-forge
    xz:              5.2.3-0            conda-forge
    zlib:            1.2.11-0           conda-forge

[michaelk@fe1 ~]$ source activate octopus
(octopus) [michaelk@fe1 ~]$ octopus
Illegal instruction (core dumped)
```

**Comment by dancooke** [comment] 2018-05-03 10:34
Which operating system are you using? I can try to look into this, but I don't maintain the Bioconda package. @chapmanb might be able to help?

**Comment by micknudsen** [comment] 2018-05-03 10:48
My example was run on Centos Linux:

```
[michaelk@fe1 ~]$ cat /proc/version
Linux version 2.6.32-642.1.1.el6.x86_64 (mockbuild@worker1.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Tue May 31 21:57:07 UTC 2016
```

**Comment by chapmanb** [comment] 2018-05-03 14:12
Michael;
Sorry about the issue, this is built on CentOS6 so should be compatible. The tricky bit is that octopus compiles against gcc 7 which get installed within the conda environment and then it should link against those. This all should happen cleanly but seems not to in your case.

A couple of thoughts:

- Could you try running directly instead of using `source activate`? I've found a lot of issues with trying to use environments if you end up having other environmental variables set or multiple environments, so that could help isolate if there is some kind of cross-environment interference going on.
- You could also take a look and be sure the libraries resolve to the correct place: `ldd /home/michaelk/anaconda3/envs/octopus/bin/octopus`. This might reveal something cross-wired. For comparison, here's what mine looks like
```
$ ldd /usr/local/share/bcbio/anaconda/bin/octopus
        linux-vdso.so.1 =>  (0x00007ffc6e9d9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f32e0cfa000)
        libboost_system.so.1.65.0 => /usr/local/share/bcbio/anaconda/bin/../lib/libboost_system.so.1.65.0 (0x00007f32e0af5000)
        libboost_filesystem.so.1.65.0 => /usr/local/share/bcbio/anaconda/bin/../lib/libboost_filesystem.so.1.65.0 (0x00007f32e08d9000)
        libboost_program_options.so.1.65.0 => /usr/local/share/bcbio/anaconda/bin/../lib/libboost_program_options.so.1.65.0 (0x00007f32e065f000)
        libboost_log_setup.so.1.65.0 => /usr/local/share/bcbio/anaconda/bin/../lib/libboost_log_setup.so.1.65.0 (0x00007f32e03b8000)
        libboost_log.so.1.65.0 => /usr/local/share/bcbio/anaconda/bin/../lib/libboost_log.so.1.65.0 (0x00007f32e00d9000)
        libboost_timer.so.1.65.0 => /usr/local/share/bcbio/anaconda/bin/../lib/libboost_timer.so.1.65.0 (0x00007f32dfed3000)
        libboost_thread.so.1.65.0 => /usr/local/share/bcbio/anaconda/bin/../lib/libboost_thread.so.1.65.0 (0x00007f32dfcb0000)
        libhts.so.2 => /usr/local/share/bcbio/anaconda/bin/../lib/libhts.so.2 (0x00007f32df9e3000)
        libstdc++.so.6 => /usr/local/share/bcbio/anaconda/bin/../lib/libstdc++.so.6 (0x00007f32df6a9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f32df3a0000)
        libgcc_s.so.1 => /usr/local/share/bcbio/anaconda/bin/../lib/libgcc_s.so.1 (0x00007f32df18e000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f32def71000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f32e17d3000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f32ded69000)
        libboost_regex.so.1.65.0 => /usr/local/share/bcbio/anaconda/bin/../lib/./libboost_regex.so.1.65.0 (0x00007f32dea67000)
        libboost_date_time.so.1.65.0 => /usr/local/share/bcbio/anaconda/bin/../lib/./libboost_date_time.so.1.65.0 (0x00007f32de854000)
        libboost_chrono.so.1.65.0 => /usr/local/share/bcbio/anaconda/bin/../lib/./libboost_chrono.so.1.65.0 (0x00007f32de64f000)
        libboost_atomic.so.1.65.0 => /usr/local/share/bcbio/anaconda/bin/../lib/./libboost_atomic.so.1.65.0 (0x00007f32de44d000)
        libicudata.so.58 => /usr/local/share/bcbio/anaconda/bin/../lib/./libicudata.so.58 (0x00007f32dc94d000)
        libicui18n.so.58 => /usr/local/share/bcbio/anaconda/bin/../lib/./libicui18n.so.58 (0x00007f32dc44d000)
        libicuuc.so.58 => /usr/local/share/bcbio/anaconda/bin/../lib/./libicuuc.so.58 (0x00007f32dc04e000)
        liblzma.so.5 => /usr/local/share/bcbio/anaconda/bin/../lib/./liblzma.so.5 (0x00007f32dbe2a000)
        libbz2.so.1.0 => /usr/local/share/bcbio/anaconda/bin/../lib/./libbz2.so.1.0 (0x00007f32dbc1a000)
        libz.so.1 => /usr/local/share/bcbio/anaconda/bin/../lib/./libz.so.1 (0x00007f32db9fd000)
        libcurl.so.4 => /usr/local/share/bcbio/anaconda/bin/../lib/./libcurl.so.4 (0x00007f32db78a000)
        libcrypto.so.1.0.0 => /usr/local/share/bcbio/anaconda/bin/../lib/./libcrypto.so.1.0.0 (0x00007f32db33a000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f32db136000)
        libssh2.so.1 => /usr/local/share/bcbio/anaconda/bin/../lib/././libssh2.so.1 (0x00007f32daefd000)
        libssl.so.1.0.0 => /usr/local/share/bcbio/anaconda/bin/../lib/././libssl.so.1.0.0 (0x00007f32dac84000)
        libgssapi_krb5.so.2 => /usr/local/share/bcbio/anaconda/bin/../lib/././libgssapi_krb5.so.2 (0x00007f32daa3c000)
        libkrb5.so.3 => /usr/local/share/bcbio/anaconda/bin/../lib/././libkrb5.so.3 (0x00007f32da771000)
        libk5crypto.so.3 => /usr/local/share/bcbio/anaconda/bin/../lib/././libk5crypto.so.3 (0x00007f32da543000)
        libcom_err.so.3 => /usr/local/share/bcbio/anaconda/bin/../lib/././libcom_err.so.3 (0x00007f32da340000)
        libkrb5support.so.0 => /usr/local/share/bcbio/anaconda/bin/../lib/./././libkrb5support.so.0 (0x00007f32da135000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f32d9f1a000)
```
Hope this helps.

**Comment by dancooke** [comment] 2018-05-28 14:17
I'm going to close this issue as the problem is not with octopus and I do not maintain the Bioconda recipe. I suggest opening an issue on the [Bioconda Github page](https://github.com/bioconda/bioconda-recipes) if the problem persists.

**Closed by dancooke** 2018-05-28 14:17 UTC
