### ISSUE TITLE
This is not a bug.  Tell us about the issues with the forest files

### ISSUE THREAD

**Issue by ghost** [luntergroup/octopus#262] opened 2023-07-12 11:11 UTC
Hello, 

title ... You published papers to promote the tool.  And it turns out to be a very nice caller. And now, no one can use it. At least give an explanation. If there is a funding issue to host the forest files, I am sure the community can find a solution. 

Please reach out if you need help. We are many who would be happy to use Octopus again. 

Thanks

**Comment by dancooke** [comment] 2023-07-12 21:42
Closing as duplicate of #259.

**Closed as completed by dancooke** 2023-07-12 21:42 UTC
Labels: duplicate, installation
