### ISSUE TITLE
germline.v0.7.4.forest.gz

### ISSUE THREAD

**Issue by gambalab** [luntergroup/octopus#261] opened 2023-06-29 09:47 UTC
Can someone share it? Since it is not possible to download from gs://luntergroup/octopus/forests/

**Comment by ghost** [comment] 2023-07-12 11:06
I have the same issue, is Octopus now an abandonware? Would be dramatic for the community. I opened an "upfront" issue... if there is a problem to host the files, like costing issue, I am certain the community can help.

**Comment by gerton** [comment] 2023-07-12 12:27
Sorry everyone, downloads got out of hand and so did the costs.  We’re working on a solution.

Best
Gerton

**Comment by jflot** [comment] 2023-07-12 12:39
I would recommend using Zenodo (https://zenodo.org/), it is completely free and datasets can be up to 50 Gb (there is even way to request them to host larger files, if needed, see https://help.zenodo.org/). As a bonus your dataset will get a DOI and a direct download link.

**Comment by ghost** [comment] 2023-07-12 14:02
The Zelondo solution seems appropriate. Do you have an idea of when the files will be available again? I need them. 

Thanks for Octopus

**Comment by dancooke** [comment] 2023-07-12 21:43
Thanks for the suggestion @jflot - I'll look into that asap. Closing as duplicate of #259.

**Closed as completed by dancooke** 2023-07-12 21:43 UTC

**Comment by gambalab** [comment] 2023-07-14 15:28
figshare is an other free solution.. plus has a DOI and can be cited :)
